### ISSUE TITLE
[IDEA] Send to Pastebin view option

### ISSUE THREAD

**Issue by c3mdigital** [mathetos/send-system-info#8]
### Use [Pastebin AP](http://pastebin.com/api) to create another view option

Using the Pastebin API plugin would create a new private paste and return the url to be given to support person.
- Another option for user working on a local or private dev environment
- Privacy concerns - don't need to reveal site domain or url **Would require a setting to hide site and home url**

**Comment by mathetos** [comment]
I don't want to include my own Developer API key with something like this, and I don't want to ask the users to create one and include it in settings.

It's an interesting idea, but unless folks start really demanding alternatives like this I'll close for now. Thanks!
